#!/bin/bash

umount $ISO_TARGET/proc &> /dev/null
umount $ISO_TARGET/dev &> /dev/null

. /etc/lunar/config
unset VERBOSE
optimize

echo "+ cleaning up file structure"
rm -rf $ISO_TARGET/var/cache/ccache/*
chroot $ISO_TARGET ccache -C
chroot $ISO_TARGET ccache -M 256M
rm -rf $ISO_TARGET/etc/ssh/ssh_host_*key $ISO_TARGET/etc/ssh/ssh_host_*key.pub
rmdir /usr/lib/locale/*

# store the list of stuff in /var/cache that needs to be resurrected:
echo "+ creating list of prepackaged modules"
mkdir -p $ISO_SOURCE/aaa_base
> $ISO_SOURCE/aaa_base/packages
for mod in $(cat conf/base.list conf/extended.list) ; do
  grep "^$mod:" $ISO_TARGET/var/state/lunar/packages >> $ISO_SOURCE/aaa_base/packages
done
# add core tools to the list:
echo "$ISO_LUNAR_MODULE:$ISO_DATE:installed:$ISO_DATE:" >> $ISO_SOURCE/aaa_base/packages

# delete CVS dirs from templates
find $ISO_TARGET -type d -name "CVS" -exec rm -rf {} \; &> /dev/null

echo "+ creating aaa_base.tar.bz2"
# gather present files
find $ISO_TARGET/{bin,boot,etc,home,lib,mnt,opt,root,sbin,srv,usr,var} | sort | uniq | sed "s:^$ISO_TARGET::g" | grep -v -e "^/var/cache/lunar/" -e "^/var/state/lunar/" -e "^/var/build/" -e "^/usr/share/doc" -e "^/usr/src/" -e "^/lib/modules/" -e "^/usr/include/" -e "^/usr/lib/perl" -e "^/var/lib/lunar" -e "^/etc/lunar" -e "^/var/spool" -e "^/var/log/" -e "^/var/tmp" -e "^/usr/share/" -e "^/var/lock/" -e "^/var/lib/" -e "^/var/run/"  > $ISO_TARGET/.present
cat $ISO_TARGET/var/log/lunar/install/* | sort | uniq > $ISO_TARGET/.tracked
diff -Bad $ISO_TARGET/.present $ISO_TARGET/.tracked | grep -e "^< " | cut -c 3- > $ISO_TARGET/.aaa_base.list
echo "/etc/lunar/local/optimizations" >> $ISO_TARGET/.aaa_base.list

# make the tarball
chroot $ISO_TARGET tar cjf /var/cache/lunar/aaa_base.tar.bz2 -T .aaa_base.list --no-recursion
mv $ISO_TARGET/var/cache/lunar/aaa_base.tar.bz2 $ISO_SOURCE/aaa_base/aaa_base.tar.bz2

# clean up
rm $ISO_TARGET/.present $ISO_TARGET/.tracked $ISO_TARGET/.aaa_base.list

