#!/bin/bash

. /etc/lunar/config

export VERBOSE=off
optimize

RESULT=0

mkdir -p ${ISO_SOURCE}/{spool,cache}

# unpack all the ISO required var/cache/lunar tarballs
# in case of file conflict preserve glibc and gcc files first!
for mod in ${ISO_LUNAR_MODULE} $(cat conf/base.list conf/base.list-$ISO_KSUFFIX conf/extended.list) ; do
  CACHE=$mod-$(module_version $mod)-$ISO_BUILD.tar.bz2
  if [ ! -f ${ISO_SOURCE}/cache/$CACHE ]; then
    echo "# $mod: $CACHE"
    cp /var/cache/lunar/$CACHE ${ISO_SOURCE}/cache/ || RESULT=1
  fi
done

# fill var/spool/lunar dir
for mod in $(cat conf/sources.list conf/sources.list-${ISO_KSUFFIX} conf/base.list conf/base.list-${ISO_KSUFFIX} conf/extended.list) ; do
  for file in $(lvu sources $mod) ; do
    if [ ! -f ${ISO_SOURCE}/spool/$file ] ; then
      echo -e "# $mod: $file"
      cp -p /var/spool/lunar/$file ${ISO_SOURCE}/spool/ || RESULT=1
    fi
  done
done

if [ "$RESULT" == 0 ]; then
    touch $ISO_TARGET/.cachefill
fi
exit $RESULT

