#!/bin/bash

. /etc/lunar/config
unset VERBOSE
optimize

BUILD_DIRECTORY=${ISO_SOURCE}/discover
cd ${ISO_SOURCE}/discover

(
  run_details discover
  unpack $(sources discover)

  cd $SOURCE_DIRECTORY
  ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --disable-curl
  make LDFLAGS=-all-static -C portability
  make LDFLAGS=-all-static -C sysdeps
  make LDFLAGS=-all-static -C lib
  make -C discover
  cd discover
  gcc -s -Wl,-O1 -o discover discover.o -ldl ${ISO_SOURCE}/discover/libcurl.a ../lib/.libs/libdiscover.a ../portability/.libs/libportability.a /usr/lib/libexpat.a ${ISO_SOURCE}/discover/libcurl.a -s -Wl,-O1 /usr/lib/libdl.a /usr/lib/libdl.a /usr/lib/libz.a  ../portability/.libs/libportability.a -lc ../lib/.libs/libdiscover.a

  cd ${ISO_SOURCE}/discover
  cp $SOURCE_DIRECTORY/discover.dtd .
  cp $SOURCE_DIRECTORY/etc/conffile.dtd .
  cp $SOURCE_DIRECTORY/etc/discover.conf .
  cp $SOURCE_DIRECTORY/discover/discover .
  rm -rf $SOURCE_DIRECTORY
)

(
  run_details discover-data
  unpack $(sources discover-data)
  cd $SOURCE_DIRECTORY
  sed -i "s:/usr/local:/usr:g" Makefile
  sed -i "s:(datadir)/tools:(prefix)/bin:g" Makefile
  make
  mkdir ${ISO_SOURCE}/discover/data
  cp *.xml ${ISO_SOURCE}/discover/data
  cd ${ISO_SOURCE}/discover
  rm -rf $SOURCE_DIRECTORY
)

