#!/bin/bash

# big bang: copy everything we need present
cp -a $ISO_SOURCE/template/etc/* $ISO_TARGET/etc/

# module related stuff
cp $ISO_TARGET/etc/skel/.bash* $ISO_TARGET/root/
cp $ISO_TARGET/etc/skel/.vimrc $ISO_TARGET/root/

# random misc stuff
mkdir -p $ISO_TARGET/var/lock/subsys
echo "Lunar Linux ${ISO_CNAME}" > $ISO_TARGET/etc/lunar.release

# rerun ldconfig to make sure we're not stale
touch $ISO_TARGET/etc/ld.so.conf
chroot $ISO_TARGET ldconfig

# prepare our moonbase!
if [ ! -f $ISO_SOURCE/template/moonbase.tar.bz2 ]; then
  echo "Cannot find template/moonbase.tar.bz2!"
  exit 1
fi

(
  echo "+ installing moonbase"
  cd $ISO_TARGET/var/lib/lunar
  tar xjf $ISO_SOURCE/template/moonbase.tar.bz2
  tar tjlf $ISO_SOURCE/template/moonbase.tar.bz2 | sed 's/^/\/var\/lib\/lunar\//g' > $ISO_TARGET/var/log/lunar/install/moonbase-${ISO_DATE}
  cd $ISO_SOURCE
  chroot $ISO_TARGET /sbin/lsh add_module moonbase installed $ISO_DATE
  echo "+ installing module.index"
  chroot $ISO_TARGET /sbin/lsh create_module_index
  echo "+ installing depends.cache"
  chroot $ISO_TARGET /sbin/lsh create_depends_cache
)
  
# manual fixes needed before compiling:
[ ! -e $ISO_TARGET/lib/cpp ] && ln -s /usr/bin/cpp $ISO_TARGET/lib/cpp
[ ! -e $ISO_TARGET/usr/include/gnu/stubs.h ] && mkdir -p $ISO_TARGET/usr/include/gnu && cp /usr/include/gnu/stubs.h $ISO_TARGET/usr/include/gnu/stubs.h

touch $ISO_TARGET/.etcf
