#!/bin/bash

# big bang: copy everything we need present
cp -a $ISO_SOURCE/template/etc/* $ISO_TARGET/etc/
chown -R root:root $ISO_TARGET/etc
chmod 0400 $ISO_TARGET/etc/shadow
chmod 0600 $ISO_TARGET/etc/lilo.conf
rm -f $ISO_TARGET/etc/mtab
ln -s /proc/mounts $ISO_TARGET/etc/mtab

# some 2.6 stuff to make sure
if [ "$ISO_KSUFFIX" == 2.6 ]; then
  mkdir -p $ISO_TARGET/sys
  sed -i 's:usbdevfs:usbfs:g' $ISO_TARGET/etc/fstab
fi

# module related stuff
cp $ISO_TARGET/etc/skel/.bash* $ISO_TARGET/root/
cp $ISO_TARGET/etc/skel/.vimrc $ISO_TARGET/root/

# random misc stuff
mkdir -p $ISO_TARGET/var/lock/subsys

# rerun ldconfig to make sure we're not stale
touch $ISO_TARGET/etc/ld.so.conf
chroot $ISO_TARGET ldconfig

(
  echo "+ installing moonbase"
  cd $ISO_TARGET/var/lib/lunar && (
    tar xjf $ISO_SOURCE/template/moonbase.tar.bz2
    tar tjf $ISO_SOURCE/template/moonbase.tar.bz2 --one-file-system | sed 's/^/\/var\/lib\/lunar\//g' > $ISO_TARGET/var/log/lunar/install/moonbase-${ISO_DATE}
  )
  chroot $ISO_TARGET /sbin/lsh add_module moonbase installed $ISO_DATE
  echo "+ installing module.index"
  chroot $ISO_TARGET /sbin/lsh create_module_index
  echo "+ installing depends.cache"
  chroot $ISO_TARGET /sbin/lsh create_depends_cache
  echo "+ installing plugins"
  chroot $ISO_TARGET /sbin/lsh update_plugins
)
  
# manual fixes needed before compiling:
[ ! -e $ISO_TARGET/lib/cpp ] && ln -s /usr/bin/cpp $ISO_TARGET/lib/cpp
[ ! -e $ISO_TARGET/usr/bin/cc ] && ln -s /usr/bin/gcc $ISO_TARGET/usr/bin/cc
[ ! -e $ISO_TARGET/usr/include/gnu/stubs.h ] && mkdir -p $ISO_TARGET/usr/include/gnu && cp /usr/include/gnu/stubs.h $ISO_TARGET/usr/include/gnu/stubs.h

echo "+ running ldconfig"
chroot $ISO_TARGET /sbin/ldconfig

chroot $ISO_TARGET lunar set ARCHIVE on


touch $ISO_TARGET/.etcf
