#!/bin/bash

if [ -e $ISO_TARGET/proc ; then
  umount $ISO_TARGET/proc &> /dev/null
  umount $ISO_TARGET/dev &> /dev/null
fi

if [ -d "$ISO_TARGET" ] ; then
  rm -rf $ISO_TARGET
fi

mkdir -p $ISO_TARGET
mkdir -p $ISO_SOURCE/{spool,cache}

touch $ISO_TARGET/.init

