#!/bin/bash

. /etc/lunar/config

echo "+ tagging release version"
echo "Lunar Linux $ISO_CNAME" > $ISO_TARGET/etc/lunar.release

echo "+ adding kernel modules"
mkdir -p $ISO_TARGET/kernels
cp $ISO_SOURCE/kernels/.kernels $ISO_TARGET/
cp -a $ISO_SOURCE/kernels/TAR/* $ISO_TARGET/kernels/
tar xj -C $ISO_TARGET -f $ISO_SOURCE/kernels/safe-modules.tar.bz2
tar xj -C $ISO_TARGET -f $ISO_SOURCE/kernels/linux-modules.tar.bz2

# copy the installed code over:
echo "+ copying installer program"
cp lunar-install/init.d/lunar-install $ISO_TARGET/etc/init.d/
ln -s /etc/init.d/lunar-install $ISO_TARGET/etc/rc2.d/S20lunar-install
cp lunar-install/sbin/lunar-install $ISO_TARGET/sbin/
sedit "s:%VERSION%:${ISO_VERSION}:g" $ISO_TARGET/sbin/lunar-install $ISO_TARGET/etc/motd
sedit "s:%CODENAME%:${ISO_CODENAME}:g" $ISO_TARGET/sbin/lunar-install $ISO_TARGET/etc/motd
sedit "s:%ISO_DATE%:${ISO_DATE}:g" $ISO_TARGET/sbin/lunar-install $ISO_TARGET/etc/motd
cp $ISO_SOURCE/lunar-install/etc/inittab $ISO_TARGET/etc/

# need more:
ln -s ../init.d/discover $ISO_TARGET/etc/rcS.d/S30discover

echo "+ adding isolinux code"
rm -rf $ISO_TARGET/isolinux
mkdir $ISO_TARGET/isolinux

cp $ISO_SOURCE/initrd/initrd $ISO_TARGET/isolinux/
cp $ISO_SOURCE/kernels/linux $ISO_TARGET/isolinux/
cp $ISO_SOURCE/kernels/safe $ISO_TARGET/isolinux/
cp $ISO_SOURCE/memtest/memtest $ISO_TARGET/isolinux/

cd $ISO_SOURCE/isolinux
for file in f{1,2,3}.txt boot.cat isolinux.bin isolinux.cfg ; do
  VERBOSE=off
  cp $file $ISO_TARGET/isolinux
  sedit "s:%VERSION%:${ISO_VERSION}:g" $ISO_TARGET/isolinux/f?.txt
  sedit "s:%CODENAME%:${ISO_CODENAME}:g" $ISO_TARGET/isolinux/f?.txt
  sedit "s:%KERNEL%:${ISO_KVER}:g" $ISO_TARGET/isolinux/f?.txt
done

echo "+ copying package listing"
cp $ISO_SOURCE/aaa_base/packages $ISO_TARGET/.packages
echo "+ copying aaa_base.tar.bz2"
cp $ISO_SOURCE/aaa_base/aaa_base.tar.bz2 $ISO_TARGET/var/cache/lunar/
echo "+ copying aaa_dev.tar.bz2"
cp $ISO_SOURCE/aaa_dev/aaa_dev.tar.bz2 $ISO_TARGET/var/cache/lunar/

cd $ISO_TARGET

touch .lunar-cd

mkisofs -o ../lunar-${ISO_VERSION}.iso -R \
        -V "Lunar-Linux ${ISO_CODENAME}" -v  \
        -d -D -N -no-emul-boot -boot-load-size 4 -boot-info-table \
        -b isolinux/isolinux.bin \
        -c isolinux/boot.cat \
        -A "Lunar-${ISO_VERSION}" .

rm -f .lunar.cd
