#!/bin/bash

. /etc/lunar/config

echo "+ tagging release version"
echo "Lunar Linux $ISO_CNAME" > $ISO_TARGET/etc/lunar.release

echo "+ adding kernel modules"
mkdir -p $ISO_TARGET/kernels
cp $ISO_SOURCE/kernels/.kernels $ISO_TARGET/
cp -a $ISO_SOURCE/kernels/TAR/* $ISO_TARGET/kernels/
tar xj -C $ISO_TARGET -f $ISO_SOURCE/kernels/safe-modules.tar.bz2
tar xj -C $ISO_TARGET -f $ISO_SOURCE/kernels/linux-modules.tar.bz2

# copy the installed code over:
echo "+ copying installer program"
cp lunar-install/init.d/lunar-install $ISO_TARGET/etc/init.d/
cp lunar-install/sbin/lunar-install $ISO_TARGET/sbin/
ln -s /etc/init.d/lunar-install $ISO_TARGET/etc/rc2.d/S20lunar-install
cp $ISO_SOURCE/lunar-install/etc/inittab $ISO_TARGET/etc/

echo "+ adding isolinux code"
rm -rf $ISO_TARGET/isolinux
mkdir $ISO_TARGET/isolinux

cp $ISO_SOURCE/initrd/initrd $ISO_TARGET/isolinux/
cp $ISO_SOURCE/kernels/linux $ISO_TARGET/isolinux/
cp $ISO_SOURCE/kernels/safe $ISO_TARGET/isolinux/
cp $ISO_SOURCE/memtest/memtest $ISO_TARGET/isolinux/

cp $ISO_SOURCE/isolinux/{f{1,2,3,4}.txt,boot.cat,isolinux.{bin,cfg},generate-iso.sh,README} $ISO_TARGET/isolinux/

echo "+ copying package listing"
cp $ISO_SOURCE/aaa_base/packages $ISO_TARGET/.packages
echo "+ copying aaa_base.tar.bz2"
cp $ISO_SOURCE/aaa_base/aaa_base.tar.bz2 $ISO_TARGET/var/cache/lunar/
echo "+ copying aaa_dev.tar.bz2"
cp $ISO_SOURCE/aaa_dev/aaa_dev.tar.bz2 $ISO_TARGET/var/cache/lunar/
echo "+ copying README"
cp $ISO_SOURCE/template/README $ISO_TARGET

for file in $ISO_TARGET/isolinux/{f{1,2,3,4}.txt,boot.cat,isolinux.{bin,cfg}} $ISO_TARGET/etc/motd $ISO_TARGET/etc/motd $ISO_TARGET/sbin/lunar-install $ISO_TARGET/README ; do
  sed -i -e "s:%VERSION%:${ISO_VERSION}:g" \
         -e "s:%CODENAME%:${ISO_CODENAME}:g" \
         -e "s:%DATE%:${ISO_DATE}:g" \
         -e "s:%KERNEL%:${ISO_KVER}:g" \
	 -e "s:%CNAME%:${ISO_CNAME}:g" $file
done

# reverse approach this:
rmdir $ISO_TARGET/var/build
cd $ISO_TARGET
touch .lunar-cd
rm .cachefill .dirs .etcf .init .proper .rebuild .unpack

mkisofs -o ../lunar-${ISO_VERSION}.iso -R \
        -V "Lunar-Linux ${ISO_CODENAME}" -v  \
        -d -D -N -no-emul-boot -boot-load-size 4 -boot-info-table \
        -b isolinux/isolinux.bin \
        -c isolinux/boot.cat \
        -A "Lunar-${ISO_VERSION}" .

touch .cachefill .dirs .etcf .init .proper .rebuild .unpack
rm -f .lunar.cd
cd $ISO_SOURCE
mkdir -p $ISO_TARGET/var/build
