#!/bin/bash

echo "+ Starting compile of kernels"
. /etc/lunar/config
export VERBOSE=off
optimize

prepare()
{
    echo "unpacking..."
    cd $ISO_SOURCE/kernels
    rm -rf linux-$ISO_KVER
    tar jxf /var/spool/lunar/linux-$ISO_KVER.tar.bz2
    cd linux-$ISO_KVER
    mkdir patches
    cd patches
    tar jxf /var/spool/lunar/ll-$ISO_PVER.tar.bz2
}

prepare_patch()
{
    cd $ISO_SOURCE/kernels/linux-$ISO_KVER
    for P in $@; do
        for PP in patches/$P/*; do
            patch_it $PP 1
	done
    done
}

prepare_options()
{
    cp $ISO_SOURCE/kernels/baseconfig $ISO_SOURCE/kernels/linux-$ISO_KVER/.config 
    for OPT in $@; do
        cat $ISO_SOURCE/kernels/config_$OPT | while read O; do 
            OPT=$(echo $O|cut -d= -f1)
            VAL=$(echo $O|cut -d= -f2)
            sedit "/$OPT=/d" $ISO_SOURCE/kernels/linux-$ISO_KVER/.config
	    sedit "/$OPT is not set/d" $ISO_SOURCE/kernels/linux-$ISO_KVER/.config
	    if [ "$VAL" == "n" ]; then
	        echo "# $OPT is not set" >> $ISO_SOURCE/kernels/linux-$ISO_KVER/.config
	    else
	        echo "$OPT=$VAL" >> $ISO_SOURCE/kernels/linux-$ISO_KVER/.config
	    fi
	done
    done
}

prepare_version()
{
    sedit "s/^EXTRAVERSION =.*/EXTRAVERSION = $1/" $ISO_SOURCE/kernels/linux-$ISO_KVER/Makefile
}

build_kernel()
{
    echo "+ building $ISO_KVER$1"
    cd $ISO_SOURCE/kernels/linux-$ISO_KVER
    yes n | make oldconfig &&
    make dep &&
    make bzImage &&
    make modules &&
    mkdir -p $ISO_SOURCE/kernels/TAR
    mkdir -p $ISO_SOURCE/kernels/BUILD
    mkdir -p $ISO_SOURCE/kernels/BUILD/boot
    mkdir -p $ISO_SOURCE/kernels/BUILD/usr/include/linux-$ISO_KVER$1
    make INSTALL_MOD_PATH=$ISO_SOURCE/kernels/BUILD modules_install
    cp arch/i386/boot/bzImage $ISO_SOURCE/kernels/BUILD/boot/$ISO_KVER$1
    if [ -n "$2" ] ; then
      cp arch/i386/boot/bzImage $ISO_SOURCE/kernels/$2
    fi
    cp System.map $ISO_SOURCE/kernels/BUILD/boot/System.map-$ISO_KVER$1
    cp .config $ISO_SOURCE/kernels/BUILD/boot/config-$ISO_KVER$1
    gzip $ISO_SOURCE/kernels/BUILD/boot/config-$ISO_KVER$1
    cp -aL $ISO_SOURCE/kernels/linux-$ISO_KVER/include/asm $ISO_SOURCE/kernels/BUILD/usr/include/linux-$ISO_KVER$1/asm
    cp -aL $ISO_SOURCE/kernels/linux-$ISO_KVER/include/linux $ISO_SOURCE/kernels/BUILD/usr/include/linux-$ISO_KVER$1/linux
    cd $ISO_SOURCE/kernels/BUILD
    tar cjf $ISO_SOURCE/kernels/TAR/$ISO_KVER$1.tar.bz2 boot/ lib/ usr/
    cd $ISO_SOURCE/kernels
    rm -rf $ISO_SOURCE/kernels/BUILD
    rm -rf $ISO_SOURCE/kernels/linux-$ISO_KVER
}

build()
{
    prepare
    prepare_patch $(echo $3)
    prepare_options $(echo $2)
    prepare_version $1
    build_kernel $1 $6
    echo "$ISO_KVER$1:$4" >> $ISO_SOURCE/kernels/.kernels
}

VERBSOSE=on

> $ISO_SOURCE/kernels/.kernels

build -safe-i386 "i386 nosmp lowmem safe" "fix" \
	"Very safe i386 (default is i686) minimal kernel (no ACPI, DMA, SMP)" "safe"
build -normal "nosmp lowmem" "fix main" \
	"Normal kernel (no SMP) (RECOMMENDED)" "linux"
build -smp-4gb "smp mem" "fix main" \
	"Normal SMP kernel with large memory (4GB)"
build -agr "nosmp lowmem lowlat" "fix main aggressive" \
	"Low latency patch"
build -agr-smp-4gb "smp mem lowlat" "fix main aggressive" \
	"Low latency patch, SMP, 4GB"
build -stb "nosmp lowmem" "fix" \
	"Minimally patched"
build -stb-smp-4gb "smp mem" "fix" \
	"Minimally patched, SMP, 4GB"
build -vnl "nosmp lowmem" "" \
	"Unpatched"
build -vnl-smp-4gb "smp mem" "" \
	"Unpatched, SMP, 4GB"
build -grs "nosmp lowmem grsec" "fix main grsecurity" \
	"Grsecurity patch"
build -grs-smp-4gb "smp mem grsec" "fix main grsecurity" \
	"Grsecurity patch, SMP, 4GB"
build -om "nosmp lowmem om" "fix om" \
	"OpenMosix clustering"
build -om-smp-4gb "smp mem om" "fix om" \
	"OpenMosix clustering, SMP, 4GB"

mkdir -p $ISO_TARGET/kernels
cp -av $ISO_SOURCE/kernels/TAR/* $ISO_TARGET/kernels/
mv $ISO_SOURCE/kernels/.kernels $ISO_TARGET/

