#!/bin/bash

. /etc/lunar/config
export VERBOSE=off

LISTS="conf/base.list conf/base.list-$ISO_KSUFFIX conf/extended.list"
MODULES="$(cat $LISTS) ${ISO_LUNAR_MODULE} kernel-headers-$ISO_KSUFFIX"

for MODULE in $MODULES ; do
	if ! module_installed $MODULE ; then
                echo "Compiling module $MODULE since we're missing a valid cache tarball"
		/sbin/lin -c $MODULE
	elif module_is_expired $MODULE ; then
		echo "Compiling module $MODULE since it is out of date"
                /sbin/lin -c $MODULE
	else
		echo "Module $MODULE appears to be installed and has a valid cache"
	fi
done

touch $ISO_TARGET/.prebuild
