#!/bin/bash

. /etc/lunar/config
export VERBOSE=off

LISTS="conf/base.list conf/base.list-$ISO_KSUFFIX conf/extended.list"
MODULES="$(cat $LISTS) ${ISO_LUNAR_MODULE} kernel-headers-$ISO_KSUFFIX"

for MODULE in $MODULES ; do
	for DEP in `lsh find_depends $MODULE` ; do
		if ! grep -q $DEP $LISTS ; then
			echo "$MODULE: Missing $DEP"
			FAILED=1
		fi
	done
done

# if [ -n "$FAILED" ]; then
# 	exit 1
# fi
