#!/bin/bash

[ ! -f $ISO_TARGET/var/lib/lunar/moonbase.tar.bz2 ] && echo "FAIL: missing moonbase" && exit 1
[ ! -f $ISO_TARGET/var/cache/lunar/$ISO_LUNAR_MODULE-$ISO_DATE-$ISO_BUILD.tar.bz2 ] && echo "FAIL: missing $ISO_LUNAR_MODULE" && exit 1
grep -q "^$ISO_LUNAR_MODULE:$ISO_DATE:" $ISO_TARGET/.packages || ( echo "FAIL: missing $ISO_LUNAR_MODULE in package list" && exit 1)

if [ -f $ISO_TARGET/.rebuild ]; then
	# first define the tests:
	TESTS=(
		"bash --version"
		"sh --version"
		"echo 1234"
		"date -u +%Y%m%d-%T"
		"awk -F: {print} /dev/null"
		"cut /dev/null -d: -f2"
		"cat /dev/null"
		"lvu installed"
		"lsh find_depends XML-Parser | wc -l | grep 4"
		"lunar set"
		"cfdisk -v"
		"fdisk -l"
		"parted -v"
		"mkfs.ext3 -V"
		"mkfs.reiserfs -V"
		"mkfs.xfs -V"
		"mkswap -V"
		"dd --version"
		"lsmod"
		"echo \"ABC\" | bzip2 -L -V > /dev/null"
		"echo \"ABC\" | gzip -L -V > /dev/null"
		"tar --version"
		)
	for TEST in "${TESTS[@]}"; do
		echo -n "$TEST: "
		if chroot $ISO_TARGET $TEST &> /dev/null ; then
			echo "OK"
		else
			echo "FAILED"
			RESULT=1
		fi
	done
	exit ${RESULT:-0}
else
	echo "Can't run tests now!"
	exit 1
fi
