#!/bin/bash

cd $ISO_SOURCE/template
wget http://lunar-linux.org/lunar/moonbase.tar.bz2
wget http://lunar-linux.org/lunar/${ISO_LUNAR_MODULE}.tar.bz2
lin moonbase
ARCHIVE=on lin ${ISO_LUNAR_MODULE}
cp /var/cache/lunar/${ISO_LUNAR_MODULE}-$(lsh echo module_version ${ISO_LUNAR_MODULE})-${ISO_BUILD}.tar.bz2 .

