#!/bin/bash

if touch / 2> /dev/null ; then
  # clean up if successfull!
  rm -f /etc/rc3.d/S99lunar-install /etc/init.d/lunar-install 1>&2 > /dev/null &
  echo "    /----------------------------------------------------------------\\"
  echo "    |                                                                |"
  echo "    |   Lunar Linux installation finished succesfully!               |"
  echo "    |                                                                |"
  echo "    |   Please log in as root and start using your system !          |"
  echo "    |                                                                |"
  echo "    | o Use 'lservices' to enable startup daemons and services       |"
  echo "    | o Use 'luser' to add new users to the system                   |"
  echo "    | o Use 'lnet' to configure your network                         |"
  echo "    | o Use 'lmodules' to load/unload kernel modules                 |"
  echo "    | o Use 'lunar' to install, remove and update packages           |"
  echo "    |                                                                |"
  echo "    |   Read 'man lfirsttime' for more tips and help                 |"
  echo "    |                                                                |"
  echo "    \\----------------------------------------------------------------/"
  # update the locate db in the background once - no need to wait on it
  updatedb 1>&2 > /dev/null &
else
  /sbin/lunar-install
fi
