#!/bin/bash

rm -f /etc/rc3.d/S99lunar-install /etc/init.d/lunar-install &> /dev/null

if [ ! -e /etc/init.d/lunar-install ] ; then

B=`echo -en '\e[1m'`
G=`echo -en '\e[32m'`
Y=`echo -en '\e[1;33m'`
E=`echo -en '\e[0m'`

cat << EOF
${B}       ________________________________________________________________
      |                                                                |
      |         ${G}${B}Lunar Linux${E} ${G}installation finished succesfully!         ${E}${B}|
      |                                                                |
      |       ${E}Please log in as root and start using your system!       ${B}|
      |                                                                |
      |    · ${E}Use '${Y}lservices${E}' to enable startup daemons and services    ${B}|
      |    · ${E}Use '${Y}luser${E}' to add new users to the system                ${B}|
      |    · ${E}Use '${Y}lnet${E}' to configure your network                      ${B}|
      |    · ${E}Use '${Y}lmodules${E}' to load/unload kernel modules              ${B}|
      |    · ${E}Use '${Y}lunar${E}' to install, remove and update packages        ${B}|
      |                                                                |
      |          Read 'man lfirsttime' for more tips and help          |
      |                                                                |
      |________________________________________________________________|${E}

EOF

  # update the locate db in the background once - no need to wait on it
  updatedb >& /dev/null &
else
  /sbin/lunar-install
fi
